// Code generated by mockery v2.22.1. DO NOT EDIT.

package mocks

import (
	domain "shipsport/internal/core/domain"

	mock "github.com/stretchr/testify/mock"
)

// ShipsPortRepository is an autogenerated mock type for the ShipsPortRepository type
type ShipsPortRepository struct {
	mock.Mock
}

// UpdateOrCreate provides a mock function with given fields: shipPort
func (_m *ShipsPortRepository) UpdateOrCreate(shipPort domain.ShipsPort) error {
	ret := _m.Called(shipPort)

	var r0 error
	if rf, ok := ret.Get(0).(func(domain.ShipsPort) error); ok {
		r0 = rf(shipPort)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewShipsPortRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewShipsPortRepository creates a new instance of ShipsPortRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewShipsPortRepository(t mockConstructorTestingTNewShipsPortRepository) *ShipsPortRepository {
	mock := &ShipsPortRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
